philosophy/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wikinavigator.urls'))
]

wikinavigator/urls.py
from django.urls import path

from . import views

app_name = 'wikinavigator'
urlpatterns = [
    path('', views.index, name='index'),
    path('path', views.path, name="path")
]

wikinavigator/models.py
from django.db import models

_WIKIPEDIA_DOMAIN = 'https://en.wikipedia.org'

# Create your models here.
class Article(models.Model):
	page_id = models.IntegerField(primary_key=True)
	canonical_title = models.TextField()
	last_revision_id = models.IntegerField()
	next_article = models.ForeignKey('self', 
		on_delete=models.SET_NULL, blank=True, null=True, default=None)

	def get_url(self):
		return _WIKIPEDIA_DOMAIN + "/wiki/" + self.canonical_title

wikinavigator/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

from . import wikipedia
from .models import Article

_PHILOSPHY_PAGE_ID = 13692155

# Load the home page with a single form
def index(request):
	return render(request, 'wikinavigator/index.html')


# Get the path to philosophy and load the page
def path(request):
	start_url = request.GET['start_url']

	current_page_metadata = wikipedia.get_metadata(start_url)

	# keep track of all visited page ids in a set
	visited_ids = set()

	# keep track of visited page metadatas in order
	page_path = [current_page_metadata]

	# set to true when execution ends in a loop
	ended_in_loop = False

	while True:

		# add current page to visited so we don't visit it again
		visited_ids.add(current_page_metadata['pageid'])

		# get the next article and its metadata
		next_article, next_article_metadata = wikipedia.get_next_article(current_page_metadata)
		page_path.append(next_article_metadata)

		# if we've already visited the next page, break the loop
		if next_article.page_id in visited_ids:
			ended_in_loop = True
			break

		# if the next page is philosophy, break the loop
		elif next_article.page_id == _PHILOSPHY_PAGE_ID:
			break

		current_page_metadata = next_article_metadata

	context = {
		'path': page_path,
		'jumps': len(page_path) - 1,
		'looped': ended_in_loop
	}

	return render(request, 'wikinavigator/path.html', context)

wikinavigator/templates/wikinavigator/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'wikinavigator/style.css' %}"
    <script src="{% static 'wikinavigator/script.js' %}"></script>

    <title>Path to Philosophy</title>
  </head>
  <body>
  	<h1 class="center">Path to Philosophy</h1>
  	<form class="center" action="{% url 'wikinavigator:path' %}" method="get">
  
  		<div class="form-group">
		    <label for="exampleInputEmail1">Start URL</label>
		    <input type="text" class="form-control" id="start_url" aria-describedby="emailHelp" placeholder="Start Page URL" name="start_url">
		    <small id="emailHelp" class="form-text text-muted">Ex. https://en.wikipedia.org/wiki/Vampire_Weekend</small>
	  	</div>
  		<input type="submit" class="btn btn-primary" value="Find Path"/>

  	</form>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

wikinavigator/templates/wikinavigator/path.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'wikinavigator/style.css' %}"
    <script src="{% static 'wikinavigator/script.js' %}"></script>

    <title>Path to Philosophy</title>
  </head>
  <body>
    <h1 class="center">Path to Philosophy</h1>
    <h2 class="center">{{jumps}} jumps</h2>
    {% if looped %}
      <h4 class="center"> Ended in a loop </h4>
    {% endif %}

    <div id="accordion" class="center">
    {% for page in path %}
      <div class="card">
        <div class="card-header" id="heading{{page.pageid}}">
          <h5 class="mb-0">
            <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapse{{page.pageid}}" aria-expanded="false" aria-controls="collapse{{page.pageid}}">
              {{page.titles.display}}
            </button>
          </h5>
        </div>
        <div id="collapse{{page.pageid}}" class="collapse" aria-labelledby="heading{{page.pageid}}" data-parent="#accordion">
          <div class="card-body row">
            {% if page.thumbnail %}
            <div class="col-3">
              <img class="fit" src="{{ page.thumbnail.source }}"/>
            </div>
            {% endif %}
            <div class="col">
              {{ page.extract_html|safe }}
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>